<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('modello', function (Blueprint $table) {
            $table->id();
            $table->string('nome', 256);
            $table->unsignedBigInteger('id_marca')->nullable();    // This references the marca table
            $table->timestamps();

            $table->foreign('id_marca')->references('id')->on('marca');
        });

        DB::table('modello')->insert([
            ['nome' => '39S3SP','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'R124LA','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'FOCUS','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MT180E30','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'PORTER','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35/E4','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DUCATO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'VITO 115 DF LONG','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 35S12','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SCUDO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35J12','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TK35','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'KANGOO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER 309 DF 37/35','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35/c15','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'VITO 109 DF LONG','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'VITO 109 DF COMPACT','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER 415 DT 43/35','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35C13','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '0','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35-10.1','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 35C12','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER 209 DF 32/30','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35C15','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TRANSIT','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MASCOTT 120','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'CANTER','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '56ANA1/130','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'CONNECT','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '65C/60/E4','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 35','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'AGMB411CDIT35','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'FOR TWO CABRIO CDI','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 40C12','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER 311 DF 37/35','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 35C15','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'F24,35 130/3','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER 211 DF 37/30','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 35C18','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MASCOTT 130','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'V.I. 56ANA1-130','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35C12','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'CRAFTER L2H2','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'PARTNER','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'AG906 ISOTERMICO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 29L12','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TRANSIT 300 M VAN 2.2','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '"DAILY  35J12','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'ribaltabile"','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'COMBO VAN NGT','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 35C13','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'BOXER 330 L2H2 120CV FAP 2.2 16V','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '"DAILY 35C15','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'con cassone grande"','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER 313 DF 37/35','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'EXPERT','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 29L10','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 35C14','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'ML80E18/P','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'BOXER','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER 413 DT 43/35','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 35S11','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 35SE4','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MASCOTT','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DOBLO\'','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'BRAVO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '"DAILY 35C17','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'con sponda"','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'PARTNER L1 5P. 1.6 16V HDI 75CV','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35J15','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'ML100E17','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MOVANO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'VIVARO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '316 F 37/35 METANO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'BOXER 330 L1H1 130CV FAP 2.2 16V HDI','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'A1','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'BOXER 333 L2H2 2.2 HDI 130CV FAP','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DUCATO 100 MULTIJET','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DOBLO\' MAXI','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MOKKA','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TRANSIT 85 T300','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER (906BA50)','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TGX 18.480T','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TRANSIT 85 T280','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DUCATO L3H2','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TGX','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER (906BA35G)','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35S14','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'FOR TWO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'FIORINO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER (906BB35G)','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DUCATO L1H1','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MASTER L3H2','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'CLASSE V','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'AD910S27','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'COOPER D','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'VIVARO L2H2','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35S13','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SCUDO L1H1','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SM1V','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TM1V','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TRANSIT L3H2','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'PUNTO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'HD001','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'COOPER D CABRIO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'PARTNER L1','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'VITO TOURER','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TIGUAN','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TRAFIC','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'Q5','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'HURACAN LP610','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'FOR FOUR COUPE\'','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '"DAILY 35C13','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'IS35CI12AA','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'con sopnda"','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '75C15','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DUCATO L2H2','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MEGANE','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'BOXER L2H2','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'Q5 SPORT','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'CLIO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'KADJAR','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35C15 ISOTERMICO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35C14','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '"DAILY 35C14 ','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'CORSA','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'BOXER 3','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'XF480','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'GLA 200','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'STELVIO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '3008','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'COMPASS','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MASTER CASS XXL','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'KARL ROCKS','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 72C17 ISO FRCX','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER 514CDI','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'DAILY 72C17 ISO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35C14 ISO FRCX','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'ML80E21','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TRAFIC L2H1','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'CROSSLAND X','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'Q3 ','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER F32/33 311','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SPRINTER L3H2','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'RANG ROVER EVOQUE','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SQ8','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '75E','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'AMG GT 43','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'Q3 SPORTBACK','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MKD 61 ME','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'MACAN GTS','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'C3 AIRCROSS','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'C8','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'H4EN3','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'IS35Cl2AA','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '"DAILY 35C12','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'EUROCARGO ML110E18T','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'XF 480','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'RENEGADE','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'TARRACO','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'IG120EL2BA','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'CAYENNE E-HYBRID ','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '208','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'PANDA','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '991 TARGA 4','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '35C16','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'A1 SPORTBACK','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'A3 SPORTBACK','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'JS50','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'AIXAM CITY PACK ','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'JS60','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '2E20 03CNN','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '3ST01-PE','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'D-TEC F DBAA','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'NS34P','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => '48 SF 15','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SD01 27 B06PN0','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SR1E 03CNN','created_at' => NOW(),'updated_at' => NOW()],
            ['nome' => 'SDP 27','created_at' => NOW(),'updated_at' => NOW()]
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('modello');
    }
};
